import type { DiplomationConfig } from "./types";

export interface LocalDocumentParams {
  /** Path to the signatory's scanned signature image (.png/.jpg) */
  signatureImagePath?: string;
  /** Path to the institution seal/stamp image (.png/.jpg) */
  sealImagePath?: string;
}

export interface GradesManagerConfig {
  apiBaseUrl: string;
  apiKey: string;
  webhookListenPort: number;
  webhookSecret: string;
  autoGenerateTranscripts: boolean;
  autoGenerateAttestations: boolean;
  autoGenerateDiplomas: boolean;
  autoOutputDir: string;
  defaultExportFormat: "zip" | "individual";
  /** Cached institution config pulled from grades-manager-api on link */
  linkedInstitutionConfig?: DiplomationConfig | null;
  /** Local-only params that can't be stored server-side */
  localDocumentParams?: LocalDocumentParams;
}

export const DEFAULT_GRADES_MANAGER_CONFIG: GradesManagerConfig = {
  apiBaseUrl: "http://localhost:3000",
  apiKey: "",
  webhookListenPort: 7842,
  webhookSecret: "",
  autoGenerateTranscripts: false,
  autoGenerateAttestations: true,
  autoGenerateDiplomas: true,
  autoOutputDir: "",
  defaultExportFormat: "zip",
  linkedInstitutionConfig: null,
  localDocumentParams: {},
};

export const GRADES_MANAGER_CONFIG_KEY = "gradesManagerConfig";
