import { useEffect } from "react";
import { GradesManagerClient } from "@/lib/grades-manager/api-client";
import {
  mapToAttestationRecords,
  mapToDiplomaRecords,
  mapToTranscriptRecords,
} from "@/lib/grades-manager/data-mapper";
import { generationQueue } from "@/lib/grades-manager/generation-queue";
import type { GradesManagerConfig } from "@/lib/grades-manager/config";

function buildPdfSettings(config: GradesManagerConfig) {
  const inst = config.linkedInstitutionConfig?.institution;
  return {
    centre: {
      nameFrench: inst?.nameFr ?? "",
      nameEnglish: inst?.nameEn ?? inst?.nameFr ?? "",
      email: inst?.contactEmail ?? "",
    },
    centreLogo: inst?.logoUrl ?? undefined,
    email: inst?.contactEmail ?? "",
  };
}

export function useGradesManagerIntegration(config: GradesManagerConfig | null) {
  useEffect(() => {
    if (!config?.apiKey || !config.apiBaseUrl) return;

    const gradesManager = (window as any).gradesManager;
    if (!gradesManager) return;

    // Handle deliberation.signed event
    const unsubDeliberation = gradesManager.onDeliberationSigned(
      async (payload: {
        deliberationId: string;
        deliberationType: string;
        institutionId: string;
      }) => {
        console.log("[GradesManager] Deliberation signed:", payload.deliberationId);
        try {
          const data = await GradesManagerClient.getDeliberation(
            payload.deliberationId,
            config,
          );

          if (config.autoGenerateAttestations) {
            const records = mapToAttestationRecords(data);
            if (records.length > 0) {
              await generationQueue.enqueue(async () => {
                console.log(`[GradesManager] Generating ${records.length} attestations...`);
                for (let i = 0; i < records.length; i++) {
                  const student = records[i];
                  try {
                    const pdfBytes = await (window as any).ipcRenderer.invoke(
                      "generate-attestation-pdf",
                      { student, settings: {}, options: {} },
                    );
                    (window as any).gradesManager.send("grades-manager:auto-generation-progress", {
                      type: "attestation",
                      current: i + 1,
                      total: records.length,
                      studentName: `${student.NOM} ${student.PRENOM}`,
                    });
                    if (config.autoOutputDir && pdfBytes) {
                      // saving handled by the generation pipeline component
                      console.log(`[GradesManager] Generated attestation for ${student.MATRICULE}`);
                    }
                  } catch (err) {
                    console.error(
                      `[GradesManager] Attestation error for ${student.MATRICULE}:`,
                      err,
                    );
                  }
                }
              });
            }
          }

          if (
            config.autoGenerateDiplomas &&
            payload.deliberationType === "graduation"
          ) {
            const records = mapToDiplomaRecords(data);
            if (records.length > 0) {
              await generationQueue.enqueue(async () => {
                console.log(`[GradesManager] Generating ${records.length} diplomas...`);
                for (let i = 0; i < records.length; i++) {
                  const student = records[i];
                  try {
                    await (window as any).ipcRenderer.invoke("generate-diploma-pdf", {
                      student,
                      settings: {},
                      options: {},
                    });
                    console.log(`[GradesManager] Generated diploma for ${student.MATRICULE}`);
                  } catch (err) {
                    console.error(
                      `[GradesManager] Diploma error for ${student.MATRICULE}:`,
                      err,
                    );
                  }
                }
              });
            }
          }
        } catch (err) {
          console.error("[GradesManager] Failed to process deliberation.signed:", err);
        }
      },
    );

    // Handle semester.grades_locked event
    const unsubSemester = gradesManager.onSemesterLocked(
      async (payload: { classId: string; institutionId: string }) => {
        if (!config.autoGenerateTranscripts) return;
        console.log("[GradesManager] Semester locked for class:", payload.classId);
        try {
          const data = await GradesManagerClient.getClassTranscripts(
            payload.classId,
            config,
          );
          const records = mapToTranscriptRecords(data);
          if (records.length > 0) {
            await generationQueue.enqueue(async () => {
              console.log(`[GradesManager] Generating ${records.length} transcripts...`);
              for (let i = 0; i < records.length; i++) {
                const student = records[i];
                try {
                  const pdfBytes = await (window as any).ipcRenderer.invoke("generate-transcript-pdf", {
                    student,
                    settings: buildPdfSettings(config),
                    options: {},
                  });
                  if (pdfBytes && config.autoOutputDir) {
                    const sep = config.autoOutputDir.includes("/") ? "/" : "\\";
                    const fname = `${student.MATRICULE}_${student.NOM}_${student.PRENOM}.pdf`.replace(/[^a-zA-Z0-9À-ÿ._-]/g, "_");
                    const outputPath = `${config.autoOutputDir}${sep}releves${sep}${fname}`;
                    await (window as any).gradesManager?.savePDF(outputPath, pdfBytes);
                  }
                  console.log(`[GradesManager] Generated transcript for ${student.MATRICULE}`);
                } catch (err) {
                  console.error(
                    `[GradesManager] Transcript error for ${student.MATRICULE}:`,
                    err,
                  );
                }
              }
            });
          }
        } catch (err) {
          console.error("[GradesManager] Failed to process semester.grades_locked:", err);
        }
      },
    );

    return () => {
      unsubDeliberation?.();
      unsubSemester?.();
    };
  }, [config]);
}
